### ISSUE TITLE
Extend selection does not work when code contains brackets in quotes

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#173]
Sending code without selection will call `extendSelection` first to determine a minimal runnable chunk from the active line. However, it does not seem to work if the code chunk contains string literals where any brackets are present.

Following is a minimal example:

```r
x <- list(list(a = 1, b = 2),
  list(a = 2, b = 3),
  list(a = 3, b = 4))
res <- local({
  lapply(x, "[[", "a")
})
```

Put cursor at `res`, and send code to active terminal, then it does not find the code chunk

```r
res <- local({
  lapply(x, "[[", "a")
})
```

rather, it only sends the first line:

```r
res <- local({
```

**Comment by andycraig** [comment]
The `extendSelection` algorithm works from the inside out, so when it encounters a quote mark it’s not certain whether it’s the start or the end of a (possibly multiline) string. In cases like this I decided to have it simply give up. I’m not planning to fix this, but it’s not ideal so if anyone would like to fix it that would of course be welcome.

Since the language server now keeps an XML syntax tree of the R code, I’ve been wondering if it would be preferable to have the task of determining which lines to send be done by the language server itself. The Julia VSCode extension does this, using a custom Language Server Protocol request.

**Comment by renkun-ken** [comment]
@andycraig Yes, that's exactly what I'm thinking of. It's also painful in languageserver to find out the same thing when the XML syntax tree is not available (code cannot be parsed). Custom language server protocol request sounds like a viable way to allow editor to take advantage of the XML syntax tree. However, the XML parse tree kept for each document in languageserver workspace may be out of sync since it only replaces the existing tree when the code is parsed. When code fails to parse, the existing tree is kept so that many LSP provides can continue to work.

**Comment by andycraig** [comment]
@renkun-ken Good point - if using the language server, we would only want to send code based on the parse tree if we know it's up to date.

**Comment by andycraig** [comment]
CC'ing @nathaneastwood as this has the potential to affect #147

**Comment by nathaneastwood** [comment]
This completely slipped my mind, sorry about that. Hopefully I'll get some time soon but I'm quite busy at the moment.

For this issue, however, I have some further comments which I think might be related. Taking the example code above, if our cursor is before `x` and I run that line (Ctrl + Enter) the cursor will go to before `res` and we can run that code block too. However let's say our cursor is anywhere that isn't before `res`, let's say before `})` on the 7th line, we will get an error because the whole chunk doesn't get sent.

```
r$> x <- list(list(a = 1, b = 2), 
      list(a = 2, b = 3), 
      list(a = 3, b = 4))                                           

r$> })                                                                          
Error: unexpected '}' in "}"
```

If we have the cursor on the 6th line, it will just execute the `lapply` and not the `res <- local({` or `})` parts.

**Comment by andycraig** [comment]
@nathaneastwood No worries at all, it definitely wasn't my intention to put pressure on you! :)

Thank you for the additional notes. They're definitely related. The algorithm tries to run the 'smallest complete chunk', so when the cursor is on a line before `res` it correctly identifies the `x` definition and sends that. I think the `lapply` line is kind of a happy accident, because it will give up when it encounters the quoted brackets and just send the current line, but that's a valid bit of code in itself. The problem comes about on the lines 5 and 7, because it fails to deal with the quoted brackets in line 6 and gives up.

**Comment by rknx** [comment]
Workaround:
I replaced '[[' with '\u005B\u005B', and now it works as expected.
This works in rstudio as well.

**Comment by rknx** [comment]
Workaround: https://github.com/randy3k/radian/issues/184#issuecomment-624370777

**Comment by renkun-ken** [comment]
Maybe we'll fix this some time.

I recommend that you select the part of code and send it to terminal without relying on automatic extendSelection algorithm in this case.

**Comment by rknx** [comment]
@renkun-ken That's what I figured. Its a pain to explain to people who I'm recommending to switch to vscode.

**Comment by renkun-ken** [comment]
@rknx This is annoying for me too.

Relying on languageserver to resolve this is also tricky since it is vscode-r-lsp that performs the communication between VSCode and languageserver, and the parsing is async with document didOpen, didSave and didChange (also with a delay now for throttle). If the document is temporarily not parse-able, then it still cannot provide a valid range of runnable expression and user has to rely on extendSelection again.

I'd prefer resolves this in extendSelection so that it could handle quotes and backticks at least for one-line string or symbol, which is sufficient for most cases.

I'll take a closer look and see if I can do anything to make it work.

**Comment by andycraig** [comment]
@renkun-ken That would be great, thank you!

**Comment by andycraig** [comment]
@renkun-ken One way to do this would wrap this `if` block https://github.com/Ikuyadeu/vscode-R/blob/413e54526f4507c62b6b270e75ea08cb510d1dc5/src/selection.ts#L218 with a check for whether `nextChar` is a quote, and if so put it in a 'quote mode' that skips all of the bracket logic until the matching quote character is encountered.

**Comment by renkun-ken** [comment]
@andycraig And it could be tricky to handle escaped quotes in strings, especially taking raw string into account. The following should include all possible one-line string/symbol we need to handle?

```r
"hello"
'hello'
'\'hello\''
"\"hello\""
r"("hello", 'world')"
`hello`
```

**Comment by andycraig** [comment]
@renkun-ken Thinking about escaped quotes was one of the reasons I decided not to deal with quotes in the first place :) To deal with them it might be worth modifying `getNextChar` so that an escaped quote can be treated as a single character.

The only other case I can think of is an escaped backquotes.

My suggestion of modifying `extendSelection` and `getNextChar` are to deal with multi-line strings as well as single-line strings. An alternative to deal with only single-line strings would be to modify `cleanLine` instead.

**Comment by renkun-ken** [comment]
@andycraig  It would be nice if both single-line and multi-line strings could be handled.

**Comment by andycraig** [comment]
@renkun-ken I agree. BTW there are unit tests for `extendSelection` here: https://github.com/Ikuyadeu/vscode-R/blob/master/test/extension.test.ts

**Comment by renkun-ken** [comment]
Just noticed a bug (#312) while `checkForBlankOrComment` mistakenly removes lines starting with `#` in multi-line strings. I'm wondering if we could simply not remove comment at all.
