### ISSUE TITLE
Duplicate handling of response update

### ISSUE THREAD

**Issue by leox31** [Ikuyadeu/vscode-R#205]
When viewing data frames or help files, I am getting double tabs open of the same thing.

**Comment by renkun-ken** [comment]
Thanks for your reporting. Would you like to share more details such as your R session info, `ls.str(getOption("vscodeR"))`.

Is it always like this or sometimes?

Would you like to open `{workspaceFolder}/.vscode/vscode-R/response.log` in VSCode and watch the content change when you call `View(mtcars)` or `?rnorm`. How many new lines are appended on each call?

**Comment by leox31** [comment]
Thank you for your reply.  This has been always the case to get double tabs of the same thing. In the response-long only one line is added for view(mtcars) or ?rnorm. However double tabs gets opened.
![SharedScreenshot](https://user-images.githubusercontent.com/23170312/73266904-c9544400-41cf-11ea-9f63-aa840dbc82fa.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/23170312/73266908-c9ecda80-41cf-11ea-9a3d-424e19dd2867.jpg)

**Comment by renkun-ken** [comment]
I'll produce a build that merges https://github.com/Ikuyadeu/vscode-R/compare/master...renkun-ken:more-logging to produce more logging to see what happens in your case.

**Comment by renkun-ken** [comment]
Would you like to unzip and install [vscode-R-1.2.2-more-logging.vsix.zip](https://github.com/Ikuyadeu/vscode-R/files/4122996/vscode-R-1.2.2-more-logging.vsix.zip).

* Run `View(mtcars)` in a fresh VSCode and R session
* Open `Help -> Toggle Developer Tools`
* Right click on the logging and `Save as` a log file.

Please upload the log file here and I'll take a closer look at what happens.

**Comment by leox31** [comment]
Thank you for your email.  Hopefully, I followed your instructions correctly. I attach the log file 
[log file2.txt](https://github.com/Ikuyadeu/vscode-R/files/4124227/log.file2.txt)

**Comment by renkun-ken** [comment]
It looks like you haven't installed the `vscode-R-1.2.2-more-logging.vsix.zip` I attached above with more logging added. Please install it and restart VSCode.

From the log file you attached, it looks like the response file is read twice, which is not the supposed behavior. To take a closer look, we need the more-logging version to be installed to see what happens on the initialization of vscode-R extension.

Perhaps I'll file a PR of the more-logging branch so that it would be easier to track down issues like this in future.

**Comment by leox31** [comment]
Unfortunately, I do not seem to be able to install the vscode-R-1.2.2-more-logging.vsix after unzipping the folder. Perhaps I am mis-understanding the installation instruction. 
![SharedScreenshot](https://user-images.githubusercontent.com/23170312/73318092-4911fb00-4230-11ea-8800-3fd898f317f3.jpg)

**Comment by renkun-ken** [comment]
Please install it by pressing Ctrl + Shift + P and running `Extensions: Install from VSIX...`

<img width="601" alt="image" src="https://user-images.githubusercontent.com/4662568/73318351-15f15b00-4274-11ea-9d26-46416734f2d0.png">

**Comment by leox31** [comment]
Thank you. I got it installed. is there any specific thing I need to do? or you will be able to monitor the issue automatically.  Incidentally, I got more lines in response-log file.

**Comment by renkun-ken** [comment]
Please attach a new log file just like you did the first time.

**Comment by leox31** [comment]
Please see attached the log file
[Log file.txt](https://github.com/Ikuyadeu/vscode-R/files/4125814/Log.file.txt)

**Comment by renkun-ken** [comment]
It looks like `responseWatcher` reacted twice on each update of `response.log` in your case. I notice that your workspace is in `OneDrive` folder which may behave differently from regular folder since there's OneDrive syncing happening in the background when any change occurs in this folder. Please try open a folder not in `OneDrive` folder (e.g. `c:\Users\ma_ab\test`) and see if the same problem occurs.

If it does not occur in non-OneDrive folder, then it's very likely that it is caused by the syncing of OneDrive software. To be compatible such behavior, we may put some id number in each response message so that we may skip those messages already handled so that it won't handle the same message twice with the presence of such behavior.

**Comment by leox31** [comment]
Thank you for your reply. As suggested, I created a new local workspace folder and added ONEDRIVE folder to it. So far so good, it does seem to work producing only one output for data sets and help files. However, I am still looking forward to the changes you planning to implement to avoid duplication in output.

**Comment by renkun-ken** [comment]
Then it is quite certain that the double-update on response is caused by OneDrive syncing. I tried opening a workspace folder in my OneDrive folder under macOS and I could reproduce it too.

I'll take a closer look at how we can avoid this soon.

**Comment by leox31** [comment]
Thank you for your help
