### ISSUE TITLE
Closures aren't recognised as functions / symbols

### ISSUE THREAD

**Issue by gowerc** [Ikuyadeu/vscode-R#322]
This may be a bit too niche to solve but thought I'd flag it anyway just encase.

Essentially closures aren't recognised as functions / symbols within vs code.  I.e.

```
x <- function(){
    function() print("hello world")
}

y <- x()
```

Then when doing a symbol search in the command palette it will only show x as a defined function

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (5 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by renkun-ken** [comment]
Do you mean

```r
x <- function(){
    function() print("hello world")
}

y <- x
```

The document symbols are provided by languageserver. Since languageserver only does static code analysis (without running the code in a live R session), we only treat explicit function definition as symbols or it will add much complexity to code analysis:

```r
fun1 <- function(...) {
  # function body
}

fun2 <- fun

fun3 <- function(x) {
  function(y) {
    x + y
  }
}

fun4 <- fun3(1)
```

If the code is run, all `fun1`, `fun2`, `fun3`, `fun4` will be functions, but at the moment we only recognize `fun1` and `fun3` as functions in static code analysis as they are explicitly defined.

Maybe in the future, we'll make the static analysis smarter but it will introduce much more complexity for only rare usage. I'm not sure if it is worth doing it in the first place.

**Comment by renkun-ken** [comment]
Would you mind if I transfer this issue to languageserver?

**Comment by gowerc** [comment]
Sure no worries (apologies at this point I am getting confused as to which functionality is coming from which package :) )

**Comment by renkun-ken** [comment]
Looks I cannot transfer this issue. Maybe you could do that yourself or simply open a new issue at languageserver.

**Comment by gowerc** [comment]
Copied over, feel free to close this issue I guess ?
