### ISSUE TITLE
Every time R terminal opens in VS Code , getting below...any idea how to fix?

### ISSUE THREAD

**Issue by mwilson19** [Ikuyadeu/vscode-R#330]
[1] FALSE
> C:/Users/.../AppData/Local/Continuum/miniconda3/Scripts/activate
Error: unexpected '/' in "C:/"
> conda activate base
Error: unexpected symbol in "conda activate"

**Comment by andycraig** [comment]
Hi @mwilson19, this is almost certainly because you're using the Python extension as well. When using a Python interpreter in a conda/virtualenv/etc. environment, the Python extension will send lines to any new terminal window to try to activate that environment. In this case, it happens after the R console has already been launched.

It would be nice if the Python extension didn't do this for new terminals created by other extensions, although I'm not sure if VS Code provides a way for extensions to check this. I will have a look at the Python extension's issue tracker to see if this has been raised there.

**Comment by andycraig** [comment]
I created an issue at the Python extension's repo: https://github.com/microsoft/vscode-python/issues/11963

**Comment by mwilson19** [comment]
Thank you, man i'm novice but still struggling with session watcher, was working fine but now the init.R doesn't seem to be working...so the plots / data frames etc.. are not rendering...code is working fine.

**Comment by renkun-ken** [comment]
@mwilson19 Does the session watcher work with Python extensions inactivated? Does your R session start normally with `init.R` sourced?

**Comment by mwilson19** [comment]
Let me try with inactivated.  Right now the vscode-R directory is located along with my working files, should it be placed somewhere else and how can i source properly?  Thank you!

**Comment by mwilson19** [comment]
Yep still not working when python ext deactivated.  I bet it's not sourcing the init.R file properly...Thank you.

**Comment by renkun-ken** [comment]
Are you creating R terminal via `R: Create R terminal` command or launch R session in the terminal yourself?

**Comment by mwilson19** [comment]
R: create R terminal, i see "R Interactive" as the terminal , then run script to plot.

**Comment by renkun-ken** [comment]
Do you see any error on R terminal startup? If not, would you please post the output of `ls.str(getOption("vscodeR"))`?

**Comment by mwilson19** [comment]
> ls.str(getOption("vscodeR")) 
attach : function ()  
capture_str : function (object)  
check_null_dev : function ()
dataview : function (x, title)  
dataview_data_type : function (x)
dataview_table : function (data)  
dir :  chr "C:\\Users\\mwilson\\OneDrive\\Documents\\Programming\\R\\.vscode\\vscode-R"
dir_plot_history :  chr "C:\\Temp\\Rtmpmg5xtt/images"
dir_session :  chr "C:\\Users\\mwilson\\OneDrive\\Documents\\Programming\\R\\.vscode\\vscode-R/6460"
globalenv_file :  chr "C:\\Users\\mwilson\\OneDrive\\Documents\\Programming\\R\\.vscode\\vscode-R/6460/globalenv.json"
new_plot : function ()  
null_dev_id :  Named int 2
null_dev_size :  num [1:2] 10.1 10.1
pid :  int 6460
platform : List of 8
 $ OS.type   : chr "windows"
 $ file.sep  : chr "/"
 $ dynlib.ext: chr ".dll"
 $ GUI       : chr "vscode"
 $ endian    : chr "little"
 $ pkgType   : chr "win.binary"
 $ path.sep  : chr ";"
 $ r_arch    : chr "x64"
plot_file :  chr "C:\\Users\\mwilson\\OneDrive\\Documents\\Programming\\R\\.vscode\\vscode-R/6460/plot.png"
plot_history_file :  NULL
plot_updated :  logi FALSE
rebind : function (sym, value, ns)
respond : function (command, ...)  
response_file :  chr "C:\\Users\\mwilson\\OneDrive\\Documents\\Programming\\R\\.vscode\\vscode-R/response.log"
tempdir :  chr "C:\\Temp\\Rtmpmg5xtt"
unbox : function (x)
update : function (...)

**Comment by mwilson19** [comment]
Thanks, and also yes, i see a [1] FALSE every time opening R terminal

**Comment by mwilson19** [comment]
Just noticing - I am seeing temp folders being created and can view the png plots , but it seems not rendering live in vs code.  Also seems I get the .vscode folder with vscode-R in several directories depending on where I started my terminal session.  Is there a way I can  source from same point everytime ?

**Comment by renkun-ken** [comment]
The `[1] FALSE` is fixed by #303 but not released yet.

Currently, session watcher only works when the R session is started from the same directory you open as the workspace root in VSCode.

And I notice that your workspace folder is in `OneDrive` which would not work in a software-syncing folder (see #179) due to lack of `watch` functionality.

Would you like to try open a folder not in OneDrive folder and also as the workspace folder in VSCode and the session watcher should work.

**Comment by mwilson19** [comment]
Ok thank you !
