### ISSUE TITLE
Feature: Expose send text delay constant as a parameter

### ISSUE THREAD

**Issue by jrounds** [Ikuyadeu/vscode-R#332]
Is it possible to expose this as a parameter:
https://github.com/Ikuyadeu/vscode-R/blob/master/src/rTerminal.ts#L119

The current one feels a little slow.  Is that as fast as it goes without error?

**Comment by andycraig** [comment]
Hi @jrounds, thank you for the suggestion. This could be exposed as a parameter. Because of changes to VS Code itself, I think sending text to VS Code's terminal has slowed down slightly since that line was added. For many users, the value could probably be safely decreased.

In the mean time, for much faster sending of text to the console we recommend [radian](https://github.com/randy3k/radian).
