### ISSUE TITLE
Changing vsc.plot has no effect

### ISSUE THREAD

**Issue by lulupointu** [Ikuyadeu/vscode-R#364]
Hi, love your extension ! I just found a little bug that caused me to downgrade just wanted to let you know. (I'm fairly knew to R so maybe their is something wrong with what I do)

**Describe the bug**
I'm trying to change the option "vsc.plot" (as suggested in #359) in order to get the plot tab to open in the second ViewColumn but the plot always appears in the Active windows. 

**To Reproduce**
1. Create a simple program
```
# This line is supposed to change the default behavior according to #359 
options(vsc.plot = "Two")

x <- c(1, 2, 3)
y <- c(1, 2, 3)
plot(x, y)
```

2. Press 'Ctrl+Shift+S'
3. See that the plot still opens in on the Active ColumnView

**Possible Fix**
I don't really know about ts but I downgraded to v1.4.1 and if works know.
I think line 132 of v1.4.1 you had `viewColumn: ViewColumn.Two`.
You changed it to `viewColumn: ViewColumn[plotView]`, (line 144 of v1.4.2)
I would gess there is an issue with ViewColumn[plotView] but I could not say more.

**Expected behavior**
plot should open a new tab in ColumnView Two

**Screenshots**
Obtained behavior:
![image](https://user-images.githubusercontent.com/5128921/85047421-17271400-b192-11ea-8079-a7031704f223.png)

Expected behavior
![image](https://user-images.githubusercontent.com/5128921/85047395-0c6c7f00-b192-11ea-97e2-3e6433898be6.png)

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - VSCode Version: 1.46.0
 - R Version: 3.4.4
 - vscode-R version: 1.4.2

**Comment by renkun-ken** [comment]
Thanks for reporting!

I could reproduce the problem. It is caused by https://github.com/Ikuyadeu/vscode-R/pull/359/files#diff-2711d8988b4edf6562a0668d7e873c13R329 by only reporting if `getOption("vsc.plot")` is `FALSE` or not when `attach()`.

This is a fairly easy fix. However, your example code 

```r
# This line is supposed to change the default behavior according to #359 
options(vsc.plot = "Two")

x <- c(1, 2, 3)
y <- c(1, 2, 3)
plot(x, y)
```

reminds me that user might set the option `vsc.plot` interactively in session and expect it to effect immediately, which is not the case at the moment. `vsc.plot` is supposed to be specified in `.Rprofile` and take effect only at session startup since there are some preparation work to be done (e.g. overwriting default device, hook new plot functions, and hack into `.External.graphics`), and it could be tricky that turning off `vsc.plot` interactively should restore what has been done.

I'll do a quick fix for your issue and you might need to write the `options(vsc.plot=?)` in your `.Rprofile` at the moment. I'll take a closer look at if we could make the option effect immediately later.

**Comment by lulupointu** [comment]
Thank you very much ! I'm glad it was easy to fix.

If I may add a suggestion, I think being able to set the option interactively might not be a huge deal.
However I do thing that you should make a section in the README explaining how to edit the .Rprofile and which options are available. Maybe I missed something but it took me a lot of poking around before finding then in #359.

**Comment by renkun-ken** [comment]
Thanks for the suggestion. I'm about to add up a section of currently available options in the README. Will include it in the PR.
