### ISSUE TITLE
Support folding of headings and code chunks in R Markdown documents

### ISSUE THREAD

**Issue by crsh** [Ikuyadeu/vscode-R#375]
First of all, thanks for this great extension. I'm exploring whether I want to switch from RStudio to VS Code and this extension is a huge help. I hope this is the right place to ask about the following.

I missing support for section folding by headings and folding of code chunks in R Markdown documents. Both work for regular Markdown documents and I can get it to work, when I add the following to my settings:

~~~
"files.associations": {
        "*.rmd": "markdown"
    }
~~~

However, by doing this I lose syntax highlighting in code chunks (and possibly other perks that this extension provides). Is there a way to have both? Can this be easily fixed by making an addition to my settings or is it more involved and a feature request for this extension?

**Comment by renkun-ken** [comment]
This could be implemented in [languageserver](https://github.com/REditorSupport/languageserver#services-implemented) if we implement [Folding Range Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange).

I have not implemented it because in VSCode the default folding range feature works well with all kinds of braces already (but of course not Rmd sections and code chunks) without a languageserver backend. If languageserver implements this folding range provider, it will *overwrite* the default folding range provider and only provides the folding ranges we define and implement. To *add* folding ranges from sections and code chunks, it seems that we have to also implement the default behavior that provides folding ranges for braces (in multi-line braces).

I've raised an issue (https://github.com/REditorSupport/languageserver/issues/289) and I'll probably implement this at some point. Any suggestions are welcome.

**Comment by igelstorm** [comment]
I just came across this issue while trying to solve the same problem (making code blocks foldable) on my own setup - I only had the R extension installed, and didn't know about [languageserver](https://github.com/REditorSupport/languageserver) or [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp).

@renkun-ken Am I right in thinking that to get this to work:

1. I need to install the [R LSP Client](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp) VS Code extension and the [languageserver](https://cran.r-project.org/web/packages/languageserver/index.html) R package
2. Currently, I need to use the development version of languageserver (installed from GitHub rather than CRAN, as described in the [README](https://github.com/REditorSupport/languageserver#languageserver-an-implementation-of-the-language-server-protocol-for-r)), since the PR that fixed this is not yet included in the latest version of languageserver (0.3.6)
3. But eventually, once a new version of languageserver is released, only 1 will be necessary, not 2?

Hope you don't mind me commenting on a closed issue, I just thought it would be helpful to clarify for myself and anyone else like me, who might have stumbled on this issue and been confused about the distinction between this project and languageserver 🙂

**Comment by renkun-ken** [comment]
Thanks for your clarification. This is indeed a bit confusing for new users.

We will make a new release of languageserver soon.
