### ISSUE TITLE
"Problems" re-appear and cannot be hidden after closing a file while it is being linted

### ISSUE THREAD

**Issue by bersbersbers** [Ikuyadeu/vscode-R#376]
**Describe the bug**
I think I observed that "Problems" are removed/hidden when a file is closed. However, when I close a file while linting is running (especially if that takes a few seconds), the problems re-appear after the file is closed and cannot be hidden. If "Show Active File Only" is checked, then these problems are not actually shown, but still counted, compare this screenshot:
![image](https://user-images.githubusercontent.com/12128514/85327675-a8b6be80-b4cf-11ea-8648-9010023bb584.png)

**To Reproduce**
1. Create and save a long-linting `.R` file
2. Make a change and save the file
3. Wait for linting to start (you'll notice the problems in the list disappear), then quickly close the file

**Do you want to fix by self? (I hope your help!)**

No

**Expected behavior**
I'd expect problems to not re-reappear for a closed file, similar to how problems are removed for a file that has completed linting at the time it is closed.

**Environment (please complete the following information):**
 - OS: Windows 10 2004, Remote SSH into Linux
 - VSCode Version: 1.46.1
 - R Version: 3.5.0
 - vscode-R version: 1.4.2

**Additional context**

I'd expect VS Code to ensure the expected behavior, but it seems to be up to the extenions to ensure this. 
https://github.com/microsoft/vscode/issues/100646

**Comment by renkun-ken** [comment]
This behavior is known and caused by how diagnositcs are managed by [languageserver](https://github.com/REditorSupport/languageserver). In languageserver, we publish diagnostics done by `lintr::lint()` for each open file in the workspace folder. At the moment, the diagnostics will be cleared if the file is not from workspace folder (i.e. from a folder other than workspace folder and its subfolders).

The use case to make diagnostics persistent is when the workspace folder is a package, it makes sense to still show diagnostics from linted but closed files.

If you prefer clearing the diagnostics when file in workspace is closed, please file an issue at [languageserver](https://github.com/REditorSupport/languageserver/issues) and link back to this one.

**Comment by bersbersbers** [comment]
I am not sure your explanation matches my issue - I can reproduce this issue for files both within and outside of the workspace. (I use a two-folder VS Code workspace based in `/home/bers/proj1`, with folders `.` and `../proj2`. I can reproduce the issue for files `/home/bers/bug.R` as well as `/home/bers/proj2/bug.R`.) So if your explanation rests heavily on the fact the file is inside the workspace folder, it's probably not the correct one.

> for each open file in the workspace folder

Once again for clarity: the file in question is not open at the time the linting problems re-appear, and it is not in the workspace folder.
