### ISSUE TITLE
Higher preview plot resolution

### ISSUE THREAD

**Issue by albert-ying** [Ikuyadeu/vscode-R#407]
**Is your feature request related to a problem? Please describe.**
When I try to print a plot to preview, very low-resolution plot generated.
**Describe the solution you'd like**
Provide setting option to set dpi for preview plot (i.e. temporary file plot.png).
**Describe alternatives you've considered**
NA
**Additional context**

**Comment by renkun-ken** [comment]
You may want to try

```
options(vsc.dev.args = list(width = 800, height = 600))
```

to modify the width and height of the png file.

or you could try `httpgd` to produce svg as introduced at https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/. However, this is not working on remote development at the moment due to https://github.com/microsoft/vscode/issues/102449.

**Comment by renkun-ken** [comment]
With #427 merged, you may want to try [httpgd](https://github.com/nx10/httpgd) for graphics.

**Comment by albert-ying** [comment]
> With #427 merged, you may want to try [httpgd](https://github.com/nx10/httpgd) for graphics.

Wow, this is really cool, thank you for notifying! Wondering will this also work on a remote server?

**Comment by renkun-ken** [comment]
Yes, it should work under remote development now.
