### ISSUE TITLE
Long input lines are do not display completely

### ISSUE THREAD

**Issue by wligtenberg** [Ikuyadeu/vscode-R#415]
I think this issue was described earlier:
https://github.com/Ikuyadeu/vscode-R/issues/57

I am experiencing that on my work (windows) machine as well. I am also using vscode-R on a linux laptop and it does not have the same issue.

The issue is, that if you open a new R terminal, the input is cut off and a `$` appears, and you can scroll through it.
The issue is, that this appears way too soon.
I verified that this does not happen with a PowerShell terminal.

To reproduce you can copy paste the following in the R terminal on Windows:
```
print("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
```
The width option has no effect on this.

I am willing to investigate more, but I am not sure where to begin.

**Environment (please complete the following information):**
 - OS: Windows
 - VSCode Version: 1.49
 - R Version: 3.6.3
 - vscode-R version: 1.4.6

**Comment by andycraig** [comment]
Hi @wligtenberg, thank you for using this extension. I believe this is because of the Windows R terminal itself. I can duplicate it in Windows 10 by opening R.exe (outside of VS Code) and pasting your example code into it. Only part of the code shows, as you report:

```
> $9012345678901234567890123456789012345678901234567890")
```

We strongly suggest using [radian](https://github.com/randy3k/radian) instead of the standard R terminal. It avoids this problem and also has a lot of other nice features.

**Comment by wligtenberg** [comment]
Thanks, I have made the switch to radian and that seems to solve the problem. You might want to add this in the Readme.md, I only now see that it is mentioned in the installation instructions for Windows. (But I never got to those, since the installation is easy enough...)
I didn't expect such a different experience from one OS to the other, using VScode and R.
