### ISSUE TITLE
Send to terminal doubles closing parentheses 

### ISSUE THREAD

**Issue by assignUser** [Ikuyadeu/vscode-R#419]
Sometimes when I send lines or blocks to the console via ctrl+enter ***without*** selecting the code, the ending parentheses will be doubled and stop the code from being run:
![image](https://user-images.githubusercontent.com/16141871/95581732-cc2f5600-0a39-11eb-9747-28353691a78b.png)
If the line/block of code is selected this never happens.
I have not managed to reproduce the bug reliably :( 
It happens often enough when executing expect_*() within test_that blocks that I assume it it has something todo with the enclosing brackets. It also only happens on the last statement in a block but does also happen when it is the only one:
```r
test_that("assertInRange works", {
  expect_silent(assertInRange(a = 1:5, range = c(0, 100)))
})
```
I have tried to reproduce the bug with similarly nested, more generic functions (also "non-function" with same arguments) but could not get the bug to show up.

**Comment by andycraig** [comment]
Hi @assignUser, thank you for reporting this. This is a weird one.

When this problem happens, if you immediately try to send the same line/block again, does the extra parenthesis appear again?

It looks like you are using radian. I think radian does some autocompletion of parenthesis etc. as well, so it is possible that this is some interaction problem between vscode-R and radian. (Although the fact that the error doesn't occur if you select the code does suggest that this is just due to vscode-R.) Next time this happens, could you try opening a plain R terminal, send the line/block to that, and see whether the extra parenthesis appears?

Extra examples might be useful too. The next few times this happens, if you could paste here the code section from the editor, the code that appears in the console, and indicate where the cursor was when you hit <kbd>Ctrl-Enter</kbd>, that would be great.

**Comment by assignUser** [comment]
I will swicht to plain r-term and try to reproduce the error.

**Comment by assignUser** [comment]
Can not reproduce at all with R.exe so it must be an issue with radian. I will look into it and open an issue there.

**Comment by andycraig** [comment]
@assignUser Thank you for investigating!

Since it only seems to occur with radian, I thought of something else. Do you have `r.bracketedPaste` enabled? If not, try enabling that and see if the problem persists.

**Comment by assignUser** [comment]
I have brackted paste activated. Interestingly, when I turn it off the error now happens more often... so very likely that it is an issue with radians input checks

**Comment by YandLiu** [comment]
I also had this problem so I turned off radian.auto.match, just add following code to the radian profile: `options(radian.auto_match = FALSE)`
But apparently this is only a temporary solution, waiting for someone to open an issue there.

**Comment by flo-schu** [comment]
I'm having the same issue. For me this happens particularly often when I have a double quote symbol followed by a closing parenthesis.

`")`

Then the the line appears in the terminal

```
c("example", "example")
")
```

The cursor then is at the beginning of the second line.

**Comment by humanfactors** [comment]
Has anyone found a solution to this yet? Starting to drive me bonkers. The `")` is exactly for me as well.

**Comment by humanfactors** [comment]
The issue resolves with `options(radian.auto_match = FALSE)`. 

However, yes the issue occurs under latest build of and `radian version: 0.5.11` and `ikuyadeu.r 2.3.1`, with `r.bracketedPaste` enabled.
