### ISSUE TITLE
Init.R overrides user's 'help_type' option

### ISSUE THREAD

**Issue by MilesMcBain** [Ikuyadeu/vscode-R#426]
**Describe the bug**
This is somewhat related to #192, since setting `options(help_type = "text")` can work around the issue of web help being inaccessible on a remote host.

Currently init.R overrides whatever the user sets for `help_type` in their .Rprofile.

**To Reproduce**
1. Set `options(help_type = "text")` in .Rprofile.
2. In an attached VSCode session, run `getOption("help_type")` which will return `"html"`

**Do you want to fix by self? (I hope your help!)**

Yes, I think I can. It seems it's just a matter of deleting this line? https://github.com/Ikuyadeu/vscode-R/blob/master/R/init.R#L25

The option doesn't appear to be read anywhere. And setting the option manually after attaching seems to work as expected.

**Expected behavior**
`getOption(help_type)` should return `"text"` after being set in the `.Rprofile`.

**Environment (please complete the following information):**
 - OS: Windows
 - VSCode Version: 1.50.1
 - R Version: 4.0.3
 - vscode-R version: 1.51

**Comment by renkun-ken** [comment]
`options(help_type = "html")` appears in the `init.R` because we want to show WebView to present the help documentation in vscode. For example, `?get` will create a http server and a web page is open to show the documentation.

I guess a fix that will make more sense is to detect the value of `getOption("help_type")` first and set to `html` if it is `NULL` (not set by user)?

**Comment by MilesMcBain** [comment]
Oh I see sorry. I thought "html" was the general default, but that is not so.

@renkun-ken I know you do a lot of remote dev, how do you set up your help? Do you specify the ports for html and does that work?

**Comment by MilesMcBain** [comment]
I am thinking we should update the remote dev section of the wiki to include this option, and any other ideas about getting help working smoothly.

**Comment by renkun-ken** [comment]
>I know you do a lot of remote dev, how do you set up your help? Do you specify the ports for html and does that work?

Just using `options(help_type="html")` in `init.R`. No need to specify ports. Calling `?` will start a http server and `browseURL` will be called then, and a WebView is created to present the URL. Due to the #380 and upstream https://github.com/microsoft/vscode/issues/102449 the help viewer is broken under remote development. User could specify a port and manually add port forwarding could make it work.

**Comment by renkun-ken** [comment]
If `options(help_type=)` is specified by user, then `init.R` won't overwrite it now.
