### ISSUE TITLE
Refactor extension.ts

### ISSUE THREAD

**Issue by Ikuyadeu** [Ikuyadeu/vscode-R#479]
Extends from #474 

`extension.ts` is literally the enter of our extension.
However, it is too complicated for newcomers.

As the first step, I want to solve the following problems.

* [ ] Remove goto label it can be simple for-statement
* [ ] Move Rmd functions to another file
* [ ] Move [completion related functions](https://github.com/ManuelHentschel/vscode-R/blob/522a21df283a2bf1516763b4a3f4415a0c6d7dc8/src/extension.ts#L296:L419) to their own file
* [ ] Move `saveDocument()` to `utils.ts`.

**Comment by ManuelHentschel** [comment]
This is definitely a good idea!

Adding to your points, I'd strongly suggest moving the [these commands](https://github.com/ManuelHentschel/vscode-R/blob/522a21df283a2bf1516763b4a3f4415a0c6d7dc8/src/extension.ts#L140:L224) to rTerminal.ts. I don't think they need to be implemented in the scope of the `activate()` function and thematically belong to the functions in rTerminal.ts anyways.

Similarly, I'd suggest moving the [completion related functions](https://github.com/ManuelHentschel/vscode-R/blob/522a21df283a2bf1516763b4a3f4415a0c6d7dc8/src/extension.ts#L296:L419) to their own file and [`saveDocument()`](https://github.com/ManuelHentschel/vscode-R/blob/522a21df283a2bf1516763b4a3f4415a0c6d7dc8/src/extension.ts#L123:L138) to utils.ts.

This would make it easier for new contributors to get an overview over what the extension does, since only the individual contributions to vscode remain in extension.ts/`activate()` and the implementation details of each feature are in their own file.

**Comment by Ikuyadeu** [comment]
@ManuelHentschel Thank you, I added your ideas.
We already have four change ideas, and it should be fixed by separated PR.

**Comment by Ikuyadeu** [comment]
Close by #525
