### ISSUE TITLE
Current GitHub release/pre-release policy

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#484]
Hi guys,

I like that there is an automated GH release approach now. However, I currently get a notification for every commit in master because it updates the "pre-release" release of the repo (I am watching "releases" for this repo).

Would it be possible to only publish automated release for actual releases? Otherwise I would need to unwatch the repo again and loose the newly gained release cycles completely again 😢

**Comment by renkun-ken** [comment]
At the moment, each merge to master will create a pre-release, which might be a bit too frequent. What about only create pre-release if the last commit message contains something to trigger this?

@ManuelHentschel

**Comment by ManuelHentschel** [comment]
> What about only create pre-release if the last commit message contains something to trigger this?

I think the main point of the development build is that users can easily install the "latest" version of the extension. If we create the pre-release only sometimes, I think we'd cause confusion, because people would still ned to download the .vsix from GitHub actions sometimes.

Toggling notifications for prereleases separately has been requested by other people as well, so maybe we get lucky and they'll introduce that feature at some point.

Another solution I'm looking into is updating the pre-release instead of making a new one. I haven't found a GitHub action to do this, so I'll try to modify some existing actions (used to create releases) to update the pre-release.
