### ISSUE TITLE
Add context menu item to show help for word at cursor

### ISSUE THREAD

**Issue by renkun-ken** [Ikuyadeu/vscode-R#528]
Now we have `R: Show Help` command and a help viewer pane. It would be nice if we also add a context menu item so that user could right click on a symbol and show help directly.

**Comment by ManuelHentschel** [comment]
Picking the right help topic might be problematic in some cases. E.g. in the following example
``` r
print <- function(...){
    base::print('NO')
}
print(123)
```
the languageserver properly picks up that `print(123)` is not referring to `base::print` and shows the correct definition instead of the help page for `base::print`.

In this example
``` r
library('igraph')
g <- igraph::graph(c(), n=1)
h <- igraph::graph(c(), n=1)
a <- union(g, h)
```

the function `union` refers `igraph::union` which is also picked up by the languageserver.


The most elegant solution might be to show a hyperlink in the hover of the languageserver, but this might be rather difficult to implement, since the languageserver is not supposed to be vscode specific.

Another approach would be to let the user pick, if multiple matching functions are found (e.g. `base::union` and `igraph::union`), though this might be annoying if you just want to quickly view a help page.
