### ISSUE TITLE
When plotting multiple plots `vscode-R` doesn't show on Viewer.

### ISSUE THREAD

**Issue by storopoli** [Ikuyadeu/vscode-R#543]
**Describe the bug**
When plotting multiple plots `vscode-R` doesn't show on Viewer.

**To Reproduce**
1. Try plotting a linear model on both Rstudio (or R terminal) and then on VS Code using `sessionWatcher: true` and `radian` as `r.term`.

```r
plot(lm(mpg ~ hp, data = mtcars))
``` 

(If related)setting.json

```json
"r.alwaysUseActiveTerminal": true,
    "r.bracketedPaste": true,
    "r.sessionWatcher": true,
    "[r]": {
        "editor.formatOnType": true,
        "editor.wordSeparators": "`~!@#%$^&*()-=+[{]}\\|;:'\",<>/?"
    },
    "r.rterm.mac": "/Users/storopoli/miniforge3/envs/r-reticulate/bin/radian",
    "r.rterm.linux": "/home/storopoli/miniforge3/envs/r-reticulate/bin/radian",
    "r.rpath.mac": "/usr/local/bin/R",
    "r.rpath.linux": "/usr/bin/R",
    "r.lsp.debug": true,
    "r.lsp.diagnostics": true,
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=/usr/local/bin/R"
    ],
```

**Expected behavior**

**Screenshots**
You can show the keybord contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**
 - OS: macOS
 -  VSCode Version: 1.52.1
 - R Version: 4.0.3
 - vscode-R version: 1.6.4

**Comment by renkun-ken** [comment]
It is because we rely on task callback to determine whether a plot is produced. Its behavior is a bit like the native plot window, i.e. the newer plot will replace the current plot.

If you need better graphics support, I recommend that you use [httpgd](https://github.com/nx10/httpgd) which works and looks much better in vscode. My [blog post](https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/) explains why.

**Comment by storopoli** [comment]
Wow! Worked lke a charm! Thank you so much!
