### ISSUE TITLE
There maybe a bug with r.runSource / Run Source

### ISSUE THREAD

**Issue by Lovely-Qianyun** [Ikuyadeu/vscode-R#563]
Hi! There maybe a bug with r.runSource / Run Source.
**Description**
I'm a beginner in Coding. After I configured this extension for R language on VSCode, I found a bug in the process of using it.  
When I finish a script in R language, naturally, I want to run the script on the terminal. So I used the `r. runsource` command. But the code didn't run as expected. Instead, VSCode just opens an R terminal. When I use the `r. runsource` command for the second time, the terminal runs the script.
PS: I opened a folder which has R source file.

**Steps to reproduce the behavior**
1. Open VSCode without starting any terminal
2. Write an R script (eg.: print("demo"))
3. `Ctrl + Shift + S` (An R Terminal named `R interactive` appears)
4. `Ctrl + Shift + S` again (The Terminal shows [1] "demo")

**Do you want to fix by self? (I hope your help!)**
I'd love to, but I'm not that good at coding and I've never been developing a VSCode extension.

**Expected behavior**
When I use `r.runSource`, it should start an `R interactive` terminal and run the script. I just need to press `Ctrl + Shift + S` for once.  

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/76724881/109172489-cb674880-77bd-11eb-9017-a36fa7aed55f.gif)

**Environment (please complete the following information):**
 - OS: Windows 10 20H2
 - VSCode Version: 1.53.2
 - R Version: 4.0.4
 - vscode-R version: 1.6.4

**Additional context**
If this is a bug, I hope you can fix it as soon as possible.
If this is not a bug, it would be great if you could tell me how to set up this extension to implement this function or develop this new function in the next version!
Thank you very much!

**Comment by renkun-ken** [comment]
Thanks for reporting!

@andycraig Maybe we need more delay before sending code after creating R terminal?

**Comment by andycraig** [comment]
I think #483 also describes the same problem, when using <kbd>Ctrl+Enter</kbd> instead of `Run Source`. I experience this too when I start a terminal with <kbd>Ctrl+Enter</kbd>.

@renkun-ken Changing the delay seemed like a good idea to me too but I tried it just now and it didn't work. Stepping through with the debugger, it looks like the problem is that `success` is actually `undefined`. The condition `!success` then evaluates as `true`, and the function returns `undefined` instead of continuing on and returning `rTerm`. So it looks like the call to `createRTerm` probably has some issue but I think I'll need to read up on async and promises etc. to make any more progress.

https://github.com/Ikuyadeu/vscode-R/blob/28d999f1e2b60d8af66d8c5aaac760d012dfa099/src/rTerminal.ts#L208-L214

**Comment by andycraig** [comment]
Thinking about this some more, I think we can just delete the `if (!success)` bit. I am putting together a PR.
