### ISSUE TITLE
Librarian package needs Radian/Rterm to run as administrator to work properly

### ISSUE THREAD

**Issue by cbarina** [Ikuyadeu/vscode-R#601]
**Describe the bug**
When using R code calling the [librarian package](https://github.com/DesiQuintans/librarian), because the R terminal isn't running in admin mode, the library won't auto-install/load packages.

**To Reproduce**
1. Enter code as follows:
`install.packages("librarian")
library(librarian)
shelf(tidyverse, codebook, readxl)
`
2. Run selection (ctrl+enter)
3. Terminal result:
![image](https://user-images.githubusercontent.com/7785375/112999048-e2a7a600-916e-11eb-928b-2c2a90ff334f.png)

**Expected behavior**
When running in radian with admin rights:
![image](https://user-images.githubusercontent.com/7785375/112999310-1d114300-916f-11eb-92c4-7a0d5fd233fa.png)

**Troubleshooting**
Have changed compatibility properties to run as administrator, but then the terminal doesn't load at all (likely due to UAC popup?)

**Environment (please complete the following information):**
 - OS: Windows
 - VSCode Version: 1.54.3
 - R Version: 4.0.4
 - vscode-R version: 1.6.5

**Comment by ManuelHentschel** [comment]
I'm not familiar with Librarian and radian, but the following steps seem to work for me to get an attached R session with admin rights:
- Rightclick on a vscode shortcut, select `Run as administrator`
- Confirm the UAC popup
- The vscode titlebar now includes `... [Administrator]`
- Run the vscode command `R: Create R terminal` (with `r.rpath.windows` empty, i.e. using the "vanilla" R path from the registry)
- Run e.g. `system('NET SESSION')` in the terminal to verify that the R session has admin rights. In a non-elevated session this will result in `"Access is denied"`, otherwise e.g. `"There are no entries in the list."`

**Comment by cbarina** [comment]
@ManuelHentschel I *swear* I had tried that and couldn't get it to work (using Radian) - but just tried it again, in case, and it did! So I'm good to go. Thanks so much!
