### ISSUE TITLE
Newby cannot run Rmd files - no Push Icon

### ISSUE THREAD

**Issue by fmartelg** [Ikuyadeu/vscode-R#64]
- VSCode Version:1.22.2
- VSCode-R Version:0.5.7
- OS Version:Windows 10

Steps to Reproduce:

1. R is installed.
1. Install VS Code
1. Install `R support for Visual Studio Code`
1. reboot
1. Create folder `test` on Desktop
1. Copy paste basic `test.Rmd` file to `test` folder
1. Open `test` folder from vscode
1. Open `test.Rmd` - there is **no** run option (Push Icon).  Cannot run.
1. New file `test.R` - there is run option (Push Icon).

I am sure I am doing something wrong. What?

User settings:
```
{
    "team.showWelcomeMessage": false,
    "[rmd]": {},
    "telemetry.enableTelemetry": false,
    "r.rterm.windows": "C:\\Program Files\\R\\R-3.4.4\\bin\\x64\\R.exe",
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--no-site-file"
    ]
}
```

**Comment by andycraig** [comment]
Hi @fmartelg, thank you for providing a very good issue write up and sorry for the very late response. There is no button to run an Rmd file. Since you created this issue, a button to knit Rmd files has been added.

The ability to run all/some chunks in an Rmd file is a feature I would like too. There is an open issue for that at #49, so I will close this issue.

Thank you again for using vscode-R!
