### ISSUE TITLE
[Feature request] Support for code sections

### ISSUE THREAD

**Issue by psychelzh** [Ikuyadeu/vscode-R#76]
See [this](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections) on `RStudio` support for code sections, which is a great way to navigate in script.

```r
# Section One ---------------------------------
 
# Section Two =================================
 
### Section Three ############################# 
```

**Comment by Ikuyadeu** [comment]
@psychelzh Thank you for your issue!
Looks interesting!
Also, Latex has similar function <https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop> .
I add this issue as help wanted.

**Comment by andycraig** [comment]
Could be done using a `DocumentSymbolProvider`.

**Comment by andycraig** [comment]
More detail on how this could be done: When a file is saved, look for section lines using a regex. Add these as symbols using `DocumentSymbolProvider`. They would then appear in the Outline and Breadcrumbs sections.

The language server also provides symbols, so it would be necessary to check that the language server symbols and the section symbols don’t conflict.

If anyone wants to have a go at implementing this, I’m happy to provide assistance.

**Comment by renkun-ken** [comment]
@andycraig I'm not sure if `DocumentSymbolProvider` is suitable for this because it does not seem to preserve order.

**Comment by andycraig** [comment]
@renkun-ken Oh! Then that might not be a good approach after all.

Markdown document sections are shown in the VSCode Outline in order: https://code.visualstudio.com/docs/languages/markdown#_outline-view The approach used for that might be more suitable.

**Comment by renkun-ken** [comment]
Just notice that the sorting order can be easily changed to position order so `DocumentSymbolProvider` should be the solution to this but user needs to use position order.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/4662568/72673615-09b51300-3aa8-11ea-9cda-2175402be073.png">

**Comment by renkun-ken** [comment]
This should be easy to implement. Do we prefer this to be implemented on vscode-R side or languageserver side? If languageserver is supposed to be pure about the language itself, then vscode-R should be the place this is implemented.

**Comment by andycraig** [comment]
If you’re keen to implement code sections that would be great!

I’m inclined to agree that vscode-R seems like the more natural place than languageserver. @randy3k What do you think?

**Comment by randy3k** [comment]
I am open to this.

**Comment by renkun-ken** [comment]
#193 is a very initial implementation of code section support. Known issues include:

* Both R LSP Client and vscode-R provides document symbols, and the outline could become 

<img width="176" alt="image" src="https://user-images.githubusercontent.com/4662568/72675487-de3e2280-3abf-11ea-91f7-aa38ffb76a1d.png">

This can be changed using `DocumentSymbolProviderMetadata`, but I'm not sure if we should merge the symbols provided by different symbol providers somehow, or maybe we should implement this in languageserver?

* As a starting point, the code section symbol uses a position which only contains the line number of the section line. However, it could also use the range that starts from the section line and ends before the next section.

**Comment by renkun-ken** [comment]
To provide unified document symbols, we better implement it in languageserver. https://github.com/REditorSupport/languageserver/pull/163 is the PR for this in languageserver which addresses all above issues.

**Comment by mik3y64** [comment]
@renkun-ken Thank you very much for implementing this pull request. Coming from RStudio, I have been missing this feature badly. Navigating large file without code sections is a nightmare for me. In [Code section support #163](https://github.com/REditorSupport/languageserver/pull/163), I see it supports one level of nested hierarchy. 

```r
# section 1----
fun1 <- function() {...}
fun2 <- function() {...}
```

# First question

does it support nested hierarchy with multiple levels? A common use case 

```r
# section 1----

fun1 <- function() {...}

fun2 <- function() {
    # case A----
    if 
    # case b----
    else if
    # case c----
    else
}
```

# Second question

Is it possible to also support R-friendly heading sections for Rmarkdown (*.rmd)?

This format shows no outline at all.

```r
# Rmarkdown heading

```{r}
plot(iris)
# ```    <- annotate "triple backticks" by commenting it out because it won't show up in Github markdown format
```

With the same code, and in `settings.json`, associate Rmarkdown with markdown file extension with `"*.rmd": "markdown"`, this format **shows markdown heading** but it **totally breaks R language server support**. No syntax highlight, no completion, and whatsoever.

Additionally, can the hash sign `#` be stripped off? In RStudio, the hash sign `#` is stripped off so instead of showing `# Rmarkdown heading`, `Rmarkdown heading` is shown. The outline view of Visual Studio Code already has built-in support of indentation and collapsible sections, the hash sign `#` is not necessary. For many levels of headings, the hash signs mess up the outlines and taking out a lot of real estate in the outline view. It would then also be consistent with code sections of `*.r` files.

**Comment by renkun-ken** [comment]
@mik3y64 Glad to know it works for you. Would you mind putting your comments at https://github.com/REditorSupport/languageserver/pull/163 which seems to be the place we discuss it further since we'll implement this feature in languageserver?

**Comment by renkun-ken** [comment]
Code sections are implemented by https://github.com/REditorSupport/languageserver/pull/163 and https://github.com/REditorSupport/languageserver/pull/186 in languageserver. Closing now.
