### ISSUE TITLE
Help  in browser

### ISSUE THREAD

**Issue by iainmstott** [Ikuyadeu/vscode-R#83]
At the moment, help docs launched from R Interactive are opened in the R-helper window. Usually these would open in the default browser: the browser offers some extra functionality, especially linking to other functions, package index, references, etc.

The reason this is happening is that R Interactive opens with `.Options$help_type` (equivalent to `options("help_type")`) `NULL` whereas it would normally be `html`, so I think this would be easy to fix by changing that. Check also another difference between `.Options` within the usual R environment and the R-Interactive environment (`.Options$na.action$na.omit` ), perhaps others (I'm not sure whether they're unique to my environment or not)

**Comment by Atrebas** [comment]
A way to circumvent this at the user level is to include `options(help_type="html")` in the `.Rprofile` file.

**Comment by andycraig** [comment]
Hi @iainmstott, if there’s a way to pass a command-line argument when starting the R terminal to set `help_type` to HTML, then the user could add that to their `r.rterm.option` setting. Otherwise, I think about the most this extension could do would be to send `options(help_type="html")` to the console once it’s started. In that case, @Atrebas’s suggestion of the user setting it in their `.Rprofile` would probably be preferable.

**Comment by iainmstott** [comment]
Thanks for the tip, but no worries, recently I've found that if you have an active terminal, then the code is sent there (and it's sent to whichever terminal was last active, which is useful and why I raised issue microsoft/vscode#78488). I don't use the 'Integrated Terminal' any more, and the standard R terminals always use html help according to my user settings.

**Comment by andycraig** [comment]
Excellent! :)

I’d like to see the active terminal highlighted as well - I hope the VSCode team add that feature at some point.

It sounds like this is sorted so I’ll close this issue.
